# 配置数据源信息
spring:
  profiles:
    # 生产环境部署时，只需将dev更改为prod即可
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource  # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver  # mysql驱动
    #url: jdbc:mysql://localhost:3306/happymall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    #password: Kexin!00
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException，默认：30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired)，默认：10min
      pool-name: DataSourceHikariCP   # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没有被使用则被释放（retired)，默认：30min
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 512000    # 上传文件大小限制为500kb，默认1M
      max-request-size: 512000 # 请求大小限制为500kb，默认10M
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html

# mybatis配置
mybatis:
  type-aliases-package: cn.coderap.pojo       # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml    # mapper映射文件
#  configuration:    # 仅在开发环境下使用，生产环境不需要
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 通用mapper配置
mapper:
  mappers: cn.coderap.my.mapper.MyMapper
  not-empty: false    # 在进行数据库操作的时候，如果判断表达式 username!=null，是否追加 username!=''。推荐手写
  identity: MYSQL

# 分页插件配置
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true

# 内置tomcat
server:
  #port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB
